[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/Pass.list"
type = "surge-ruleset"

[[rulesets]]
group = "Manual"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/process_name/ProxyProc.list"
type = "surge-ruleset"
[[rulesets]]
group = "Manual"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/ProxyList.list"
type = "surge-ruleset"

[[rulesets]]
group = "Telegram"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/process_name/TelegramProc.list"
type = "surge-ruleset"
[[rulesets]]
group = "Telegram"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml"
type = "clash-classic"

[[rulesets]]
group = "Google"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/YouTube.yaml"
type = "clash-classic"
[[rulesets]]
group = "Google"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Music/YouTubeMusic.yaml"
type = "clash-classic"
[[rulesets]]
group = "Google"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/process_name/GoogleProc.list"
type = "surge-ruleset"
[[rulesets]]
group = "Google"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/Google.list"
type = "surge-ruleset"

[[rulesets]]
group = "Netflix"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml"
type = "clash-classic"
[[rulesets]]
group = "Netflix"
ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/Fast.list"
type = "surge-ruleset"

# [[rulesets]]
# group = "GMedia"
# ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml"
# type = "clash-classic"
[[rulesets]]
group = "GMedia"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/DisneyPlus.yaml"
type = "clash-classic"
# [[rulesets]]
# group = "CMedia"
# ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml"
# type = "clash-classic"
# [[rulesets]]
# group = "CMedia"
# ruleset = "https://raw.iqiq.io/hardy-one/profile/master/ruleset/process_name/BiliBili.list"
# type = "surge-ruleset"
[[rulesets]]
group = "CMedia"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.iqiq.io/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml"
type = "clash-ipcidr"

# [[rulesets]]
# group = "DIRECT"
# ruleset = "https://raw.iqiq.io/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml"
# type = "clash-ipcidr"

[[rulesets]]
group = "Manual"
ruleset = "[]FINAL"
